title: Dr Gerald Moore
logo: /assets/gerald-headshot.png
description: Doctorate in Neurotechnology | Data Scientist | Machine Learning Engineer | Developer | Researcher
email: gerald.moore.mail@gmail.com
linkedin: https://linkedin.com/in/gerald-moore
github_one: https://github.com/geraldmoore
github_two: https://github.com/gm515
cv_download: /cv/gerald_moore_cv.pdf
show_contents: true
remote_theme: pages-themes/minimal@v0.2.0
